# Generated by Django 4.1.3 on 2022-12-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_druzyna_rename_gun_text_gun_gun_name_osoba_choice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='druzyna',
            options={'verbose_name_plural': 'Druzyny'},
        ),
        migrations.AlterField(
            model_name='osoba',
            name='miesiac_urodzenia',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1),
        ),
    ]
